line.bot:
  channel-token: 'Y28nIH0nDbOR1gJB+RkSSU8b5N+d2zZsF2cobAsgAOfOu5qWZOZO6nFhUobREXoZWDY8igkYt2aqO3+uzkXhZNBprN19uj4PzKkCekd63QqNWnGBN7QysWF2x/hnaHjhOWK/q4kqBl2xePh9H7htMwdB04t89/1O/w1cDnyilFU='
  channel-secret: '76e4119c71511ae55d22ca7c488bd664'
  handler.path: /callback

# To remove Client wire logs. Please comment out following lines.
# See: https://docs.spring.io/spring-boot/docs/current/reference/html/howto-logging.html
#
#logging.level:
#   com.linecorp.bot.client.wire: INFO
